# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockrootproject

on:
  push:
    branches:
      - dev-root-michael
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eb78ed13ce39466fa14d791006211141 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ce2c7f588ebb4f72b45c5b0d5700bc1d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_eb78ed13ce39466fa14d791006211141 }}/drtmbg/image-mf-web-root-config:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockrootproject'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a732a04725b49f8bcd5ca4cfab0e41a }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_eb78ed13ce39466fa14d791006211141 }}/drtmbg/image-mf-web-root-config:${{ github.sha }}'